"""Added ISBN column to all book tables

Revision ID: 75f480398bf3
Revises: 11f97d92b20f
Create Date: 2022-08-23 12:48:40.655419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f480398bf3'
down_revision = '11f97d92b20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_books', sa.Column('isbn', sa.Integer(), nullable=False))
    op.add_column('audio_books_for_approval', sa.Column('isbn', sa.Integer(), nullable=False))
    op.add_column('digital_books', sa.Column('isbn', sa.Integer(), nullable=False))
    op.add_column('digital_books_for_approval', sa.Column('isbn', sa.Integer(), nullable=False))
    op.add_column('reading_books', sa.Column('isbn', sa.Integer(), nullable=False))
    op.add_column('reading_books_for_approval', sa.Column('isbn', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_books_for_approval', 'isbn')
    op.drop_column('reading_books', 'isbn')
    op.drop_column('digital_books_for_approval', 'isbn')
    op.drop_column('digital_books', 'isbn')
    op.drop_column('audio_books_for_approval', 'isbn')
    op.drop_column('audio_books', 'isbn')
    # ### end Alembic commands ###
