"""empty message

Revision ID: 8edf03215708
Revises: 
Create Date: 2022-08-19 17:17:11.451074

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8edf03215708"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=35), nullable=False),
        sa.Column("last_name", sa.String(length=35), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "role",
            sa.Enum("user", "checker", "admin", name="userroles"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "audio_books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("author_first_name", sa.String(length=35), nullable=False),
        sa.Column("author_last_name", sa.String(length=35), nullable=False),
        sa.Column("genre", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("reader_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audio_books_for_approval",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("author_first_name", sa.String(length=35), nullable=False),
        sa.Column("author_last_name", sa.String(length=35), nullable=False),
        sa.Column("genre", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("reader_name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="status"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "checker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=35), nullable=False),
        sa.Column("last_name", sa.String(length=35), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "role",
            sa.Enum("user", "checker", "admin", name="userroles"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "reading_books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("author_first_name", sa.String(length=35), nullable=False),
        sa.Column("author_last_name", sa.String(length=35), nullable=False),
        sa.Column("genre", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("original_language", sa.String(length=20), nullable=True),
        sa.Column("publish_language", sa.String(length=20), nullable=False),
        sa.Column("edition", sa.Integer(), nullable=False),
        sa.Column(
            "paper_format_cover", sa.Enum("soft", "hard", name="covers"), nullable=True
        ),
        sa.Column("digital_format", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reading_books_for_approval",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("author_first_name", sa.String(length=35), nullable=False),
        sa.Column("author_last_name", sa.String(length=35), nullable=False),
        sa.Column("genre", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("original_language", sa.String(length=20), nullable=True),
        sa.Column("publish_language", sa.String(length=20), nullable=False),
        sa.Column("edition", sa.Integer(), nullable=False),
        sa.Column(
            "paper_format_cover", sa.Enum("soft", "hard", name="covers"), nullable=True
        ),
        sa.Column("digital_format", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="status"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "standard_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=35), nullable=False),
        sa.Column("last_name", sa.String(length=35), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "role",
            sa.Enum("user", "checker", "admin", name="userroles"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("standard_user")
    op.drop_table("reading_books_for_approval")
    op.drop_table("reading_books")
    op.drop_table("checker")
    op.drop_table("audio_books_for_approval")
    op.drop_table("audio_books")
    op.drop_table("admin")
    # ### end Alembic commands ###
