"""changed column cover to cover_photo_url

Revision ID: a6d425303bf7
Revises: 13ca5074f355
Create Date: 2022-09-01 16:18:00.578724

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a6d425303bf7'
down_revision = '13ca5074f355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_books', sa.Column('cover_photo_url', sa.String(length=255), nullable=False))
    op.drop_column('audio_books', 'cover')
    op.add_column('audio_books_for_approval', sa.Column('cover_photo_url', sa.String(length=255), nullable=False))
    op.drop_column('audio_books_for_approval', 'cover')
    op.add_column('digital_books', sa.Column('cover_photo_url', sa.String(length=255), nullable=False))
    op.drop_column('digital_books', 'cover')
    op.add_column('digital_books_for_approval', sa.Column('cover_photo_url', sa.String(length=255), nullable=False))
    op.drop_column('digital_books_for_approval', 'cover')
    op.add_column('reading_books', sa.Column('cover_photo_url', sa.String(length=255), nullable=False))
    op.drop_column('reading_books', 'cover')
    op.add_column('reading_books_for_approval', sa.Column('cover_photo_url', sa.String(length=255), nullable=False))
    op.drop_column('reading_books_for_approval', 'cover')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_books_for_approval', sa.Column('cover', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('reading_books_for_approval', 'cover_photo_url')
    op.add_column('reading_books', sa.Column('cover', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('reading_books', 'cover_photo_url')
    op.add_column('digital_books_for_approval', sa.Column('cover', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('digital_books_for_approval', 'cover_photo_url')
    op.add_column('digital_books', sa.Column('cover', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('digital_books', 'cover_photo_url')
    op.add_column('audio_books_for_approval', sa.Column('cover', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('audio_books_for_approval', 'cover_photo_url')
    op.add_column('audio_books', sa.Column('cover', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('audio_books', 'cover_photo_url')
    # ### end Alembic commands ###
