"""test with association tables.

Revision ID: b8e66687f376
Revises: 812e197efb84
Create Date: 2022-08-24 17:42:32.253514

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b8e66687f376"
down_revision = "812e197efb84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_audio_books_associations",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("audio_book_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["audio_book_id"],
            ["audio_books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["standard_user.id"],
        ),
    )
    op.create_table(
        "users_digital_books_associations",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("digital_book_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["digital_book_id"],
            ["digital_books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["standard_user.id"],
        ),
    )
    op.create_table(
        "users_reading_books_associations",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("reading_book_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reading_book_id"],
            ["reading_books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["standard_user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_reading_books_associations")
    op.drop_table("users_digital_books_associations")
    op.drop_table("users_audio_books_associations")
    # ### end Alembic commands ###
