"""removed autho's model

Revision ID: bfbf1586baa3
Revises: 75f480398bf3
Create Date: 2022-08-23 13:02:13.460812

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bfbf1586baa3'
down_revision = '75f480398bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_books', sa.Column('author_name', sa.String(length=100), nullable=False))
    op.drop_constraint('audio_books_author_id_fkey', 'audio_books', type_='foreignkey')
    op.drop_column('audio_books', 'author_id')
    op.add_column('audio_books_for_approval', sa.Column('author_name', sa.String(length=100), nullable=False))
    op.add_column('digital_books', sa.Column('author_name', sa.String(length=100), nullable=False))
    op.drop_constraint('digital_books_author_id_fkey', 'digital_books', type_='foreignkey')
    op.drop_column('digital_books', 'author_id')
    op.add_column('digital_books_for_approval', sa.Column('author_name', sa.String(length=100), nullable=False))
    op.add_column('reading_books', sa.Column('author_name', sa.String(length=100), nullable=False))
    op.drop_constraint('reading_books_author_id_fkey', 'reading_books', type_='foreignkey')
    op.drop_column('reading_books', 'author_id')
    op.add_column('reading_books_for_approval', sa.Column('author_name', sa.String(length=100), nullable=False))
    op.drop_table('authors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_books_for_approval', 'author_name')
    op.add_column('reading_books', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reading_books_author_id_fkey', 'reading_books', 'authors', ['author_id'], ['id'])
    op.drop_column('reading_books', 'author_name')
    op.drop_column('digital_books_for_approval', 'author_name')
    op.add_column('digital_books', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('digital_books_author_id_fkey', 'digital_books', 'authors', ['author_id'], ['id'])
    op.drop_column('digital_books', 'author_name')
    op.drop_column('audio_books_for_approval', 'author_name')
    op.add_column('audio_books', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('audio_books_author_id_fkey', 'audio_books', 'authors', ['author_id'], ['id'])
    op.drop_column('audio_books', 'author_name')
    op.create_table('authors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('nationality', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reading_books_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('digital_books_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audio_books_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['audio_books_id'], ['audio_books.id'], name='authors_audio_books_id_fkey'),
    sa.ForeignKeyConstraint(['digital_books_id'], ['digital_books.id'], name='authors_digital_books_id_fkey'),
    sa.ForeignKeyConstraint(['reading_books_id'], ['reading_books.id'], name='authors_reading_books_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='authors_pkey')
    )
    # ### end Alembic commands ###
