"""isbn columns delete

Revision ID: c61f4e8ad700
Revises: b8e66687f376
Create Date: 2022-08-24 21:10:41.517470

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c61f4e8ad700'
down_revision = 'b8e66687f376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_books', 'isbn')
    op.drop_column('audio_books_for_approval', 'isbn')
    op.drop_column('digital_books', 'isbn')
    op.drop_column('digital_books_for_approval', 'isbn')
    op.drop_column('reading_books', 'isbn')
    op.drop_column('reading_books_for_approval', 'isbn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_books_for_approval', sa.Column('isbn', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reading_books', sa.Column('isbn', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('digital_books_for_approval', sa.Column('isbn', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('digital_books', sa.Column('isbn', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('audio_books_for_approval', sa.Column('isbn', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('audio_books', sa.Column('isbn', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
