"""separate digital book and reading book

Revision ID: ff718a2b658a
Revises: 8edf03215708
Create Date: 2022-08-20 19:05:11.160333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff718a2b658a'
down_revision = '8edf03215708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_books_for_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('author_first_name', sa.String(length=35), nullable=False),
    sa.Column('author_last_name', sa.String(length=35), nullable=False),
    sa.Column('genre', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('original_language', sa.String(length=20), nullable=True),
    sa.Column('publish_language', sa.String(length=20), nullable=False),
    sa.Column('edition', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('reading_books_for_approval', 'digital_format')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_books_for_approval', sa.Column('digital_format', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('digital_books_for_approval')
    # ### end Alembic commands ###
